"""Email delivery for reports."""

import logging
from pathlib import Path

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Attachment, FileContent, FileName, FileType, Disposition
import base64

from src.config import settings

logger = logging.getLogger(__name__)


def send_report_email(
    to_emails: list[str],
    subject: str,
    body: str,
    pdf_path: str | None = None,
) -> bool:
    """Send a report via email with optional PDF attachment."""
    if not settings.sendgrid_api_key:
        logger.warning("SendGrid not configured, skipping email")
        return False

    if settings.demo_mode:
        logger.info(f"Demo mode: Would send email to {to_emails}")
        return True

    try:
        message = Mail(
            from_email=settings.from_email,
            to_emails=to_emails,
            subject=subject,
            html_content=body,
        )

        # Add PDF attachment if provided
        if pdf_path and Path(pdf_path).exists():
            with open(pdf_path, "rb") as f:
                pdf_data = f.read()

            encoded_pdf = base64.b64encode(pdf_data).decode()
            attachment = Attachment(
                FileContent(encoded_pdf),
                FileName(Path(pdf_path).name),
                FileType("application/pdf"),
                Disposition("attachment"),
            )
            message.attachment = attachment

        sg = SendGridAPIClient(settings.sendgrid_api_key)
        response = sg.send(message)

        if response.status_code in [200, 202]:
            logger.info(f"Email sent successfully to {to_emails}")
            return True
        else:
            logger.error(f"Email failed with status {response.status_code}")
            return False

    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False


def send_scheduled_report(report) -> bool:
    """Send a scheduled report to default recipients."""
    if not settings.default_recipients:
        logger.warning("No default recipients configured")
        return False

    recipients = [r.strip() for r in settings.default_recipients.split(",")]

    body = f"""
    <html>
    <body style="font-family: -apple-system, BlinkMacSystemFont, sans-serif;">
        <h2 style="color: {settings.primary_color};">Your Report is Ready</h2>
        <p>Hello,</p>
        <p>Your scheduled report "{report.title}" has been generated.</p>
        <p>Please find the PDF attached to this email.</p>
        <hr style="border: none; border-top: 1px solid #e5e5e5;">
        <p style="color: #666; font-size: 12px;">
            Generated by ReportGen for {settings.company_name}
        </p>
    </body>
    </html>
    """

    return send_report_email(
        to_emails=recipients,
        subject=f"[ReportGen] {report.title}",
        body=body,
        pdf_path=report.pdf_path,
    )
